@echo off
REM ==================================================================
REM  Eye Data Labeller -- one-shot installer for Windows.
REM
REM  Steps:
REM    1. Download Miniforge into %USERPROFILE%\miniforge3 if missing.
REM    2. Create / update the `eye-labeller` conda env from
REM       environment.yml (CPU PyTorch baseline -- same on every OS).
REM    3. Detect NVIDIA GPU via nvidia-smi.exe; if present, swap to
REM       the CUDA-enabled pip wheel of PyTorch.
REM    4. Drop a launcher at %USERPROFILE%\Desktop\EyeDataLabeller.bat.
REM
REM  CUDA WHEEL VERSION:
REM    Default cu124 (CUDA 12.4) works with NVIDIA driver >=550.
REM    For older drivers, edit CUDA_INDEX below to cu121 (driver
REM    >=525). Open Command Prompt and run `nvidia-smi` to see your
REM    driver version on the top line of the output.
REM ==================================================================

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
for %%i in ("%SCRIPT_DIR%..") do set "PROJECT_ROOT=%%~fi"
set "MINIFORGE_DIR=%USERPROFILE%\miniforge3"
set "ENV_NAME=eye-labeller"
set "DESKTOP_LAUNCHER=%USERPROFILE%\Desktop\EyeDataLabeller.bat"

REM CUDA wheel index. Change to cu121 for older drivers (see header).
set "CUDA_INDEX=https://download.pytorch.org/whl/cu124"

echo [install] PROJECT_ROOT = %PROJECT_ROOT%
echo [install] MINIFORGE_DIR = %MINIFORGE_DIR%

REM ---- 1. Miniforge ------------------------------------------------
if exist "%MINIFORGE_DIR%\Scripts\conda.exe" (
    echo [install] Miniforge already at %MINIFORGE_DIR% -- reusing.
) else (
    echo [install] Downloading Miniforge installer...
    set "MINIFORGE_URL=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe"
    set "TMP_EXE=%TEMP%\miniforge-installer.exe"
    powershell -Command "Invoke-WebRequest -Uri '%MINIFORGE_URL%' -OutFile '%TMP_EXE%'" || goto :fail
    echo [install] Installing Miniforge silently...
    start /wait "" "%TMP_EXE%" /S /AddToPath=0 /RegisterPython=0 /D=%MINIFORGE_DIR%
    del "%TMP_EXE%"
)

REM Make conda available in this shell.
call "%MINIFORGE_DIR%\Scripts\activate.bat" || goto :fail

REM ---- 2. Conda env ------------------------------------------------
if not exist "%PROJECT_ROOT%\environment.yml" (
    echo [install] FAILED: environment.yml not found at %PROJECT_ROOT%
    goto :fail
)

call conda env list | findstr /B /C:"%ENV_NAME% " >nul
if errorlevel 1 (
    echo [install] Creating '%ENV_NAME%' env from environment.yml  (5-15 min)
    call conda env create -n "%ENV_NAME%" -f "%PROJECT_ROOT%\environment.yml" || goto :fail
) else (
    echo [install] Updating existing '%ENV_NAME%' env from environment.yml
    call conda env update -n "%ENV_NAME%" -f "%PROJECT_ROOT%\environment.yml" --prune || goto :fail
)

REM ---- 3. GPU detection + CUDA PyTorch swap -----------------------
REM env.yml ships CPU PyTorch as the baseline so every platform starts
REM the same. On Windows + NVIDIA we swap to the CUDA wheel.
REM --force-reinstall overwrites conda's CPU torch; --no-deps avoids
REM disturbing numpy / scipy.
where nvidia-smi >nul 2>&1
if errorlevel 1 (
    echo [install] No NVIDIA GPU detected -- keeping CPU PyTorch.
    echo [install]   App will run on CPU. Slower than GPU but works.
) else (
    nvidia-smi >nul 2>&1
    if errorlevel 1 (
        echo [install] nvidia-smi present but failed -- driver issue?
        echo [install] Skipping CUDA swap; app will use CPU.
    ) else (
        echo [install] NVIDIA GPU detected -- swapping to CUDA PyTorch
        echo [install]   Using wheel index %CUDA_INDEX%
        call conda activate "%ENV_NAME%"
        pip install --force-reinstall --no-deps torch torchvision --index-url %CUDA_INDEX% || (
            echo [install] CUDA PyTorch install FAILED -- app will fall back to CPU.
            echo [install] Check driver/CUDA compatibility per the header notes.
        )
        call conda deactivate
    )
)

REM ---- 4. Desktop launcher ----------------------------------------
echo [install] Writing launcher to %DESKTOP_LAUNCHER%
(
    echo @echo off
    echo REM Auto-generated by deploy\install_windows.bat
    echo call "%MINIFORGE_DIR%\Scripts\activate.bat" %ENV_NAME%
    echo cd /d "%PROJECT_ROOT%"
    echo python main.py %%*
) > "%DESKTOP_LAUNCHER%"

REM ---- 5. Optional SAM-HeLa checkpoint path -----------------------
echo.
echo [install] Optional: if you already have sam_hela\best.pt on disk,
echo [install] you can point the app at it now. Press Enter to skip --
echo [install] you can configure it later in the app's I/O settings.
set /p "MODEL_PATH=  Path to best.pt (or empty to skip): "
if not "%MODEL_PATH%"=="" (
    call conda activate "%ENV_NAME%"
    python "%SCRIPT_DIR%configure_model.py" "%MODEL_PATH%" || (
        echo [install] (path not saved; you can set it later in the app settings)
    )
)

echo [install] Done. Double-click EyeDataLabeller on your Desktop to launch.
endlocal
exit /b 0

:fail
echo [install] FAILED. See messages above.
endlocal
exit /b 1
