@echo off
REM ==================================================================
REM  Eye Data Labeller -- one-shot installer for Windows.
REM
REM  Steps:
REM    1. Download Miniforge into %USERPROFILE%\miniforge3 if missing.
REM    2. Create / update the `eye-labeller` conda env from
REM       environment.yml in the project root.
REM    3. Drop a launcher at the user's Desktop:
REM       %USERPROFILE%\Desktop\EyeDataLabeller.bat
REM
REM  NVIDIA-GPU users: after this finishes, open the env and replace
REM  the PyTorch wheels with CUDA-enabled ones:
REM
REM       conda activate eye-labeller
REM       pip uninstall torch torchvision
REM       pip install torch torchvision --index-url https://download.pytorch.org/whl/cu121
REM
REM ==================================================================

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
for %%i in ("%SCRIPT_DIR%..") do set "PROJECT_ROOT=%%~fi"
set "MINIFORGE_DIR=%USERPROFILE%\miniforge3"
set "ENV_NAME=eye-labeller"
set "DESKTOP_LAUNCHER=%USERPROFILE%\Desktop\EyeDataLabeller.bat"

echo [install] PROJECT_ROOT = %PROJECT_ROOT%
echo [install] MINIFORGE_DIR = %MINIFORGE_DIR%

REM ---- 1. Miniforge ------------------------------------------------
if exist "%MINIFORGE_DIR%\Scripts\conda.exe" (
    echo [install] Miniforge already at %MINIFORGE_DIR% -- reusing.
) else (
    echo [install] Downloading Miniforge installer...
    set "MINIFORGE_URL=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe"
    set "TMP_EXE=%TEMP%\miniforge-installer.exe"
    powershell -Command "Invoke-WebRequest -Uri '%MINIFORGE_URL%' -OutFile '%TMP_EXE%'" || goto :fail
    echo [install] Installing Miniforge silently...
    start /wait "" "%TMP_EXE%" /S /AddToPath=0 /RegisterPython=0 /D=%MINIFORGE_DIR%
    del "%TMP_EXE%"
)

REM Make conda available in this shell.
call "%MINIFORGE_DIR%\Scripts\activate.bat" || goto :fail

REM ---- 2. Conda env ------------------------------------------------
if not exist "%PROJECT_ROOT%\environment.yml" (
    echo [install] FAILED: environment.yml not found at %PROJECT_ROOT%
    goto :fail
)

call conda env list | findstr /B /C:"%ENV_NAME% " >nul
if errorlevel 1 (
    echo [install] Creating '%ENV_NAME%' env from environment.yml  (5-15 min)
    call conda env create -n "%ENV_NAME%" -f "%PROJECT_ROOT%\environment.yml" || goto :fail
) else (
    echo [install] Updating existing '%ENV_NAME%' env from environment.yml
    call conda env update -n "%ENV_NAME%" -f "%PROJECT_ROOT%\environment.yml" --prune || goto :fail
)

REM ---- 3. Desktop launcher ----------------------------------------
echo [install] Writing launcher to %DESKTOP_LAUNCHER%
(
    echo @echo off
    echo REM Auto-generated by deploy\install_windows.bat
    echo call "%MINIFORGE_DIR%\Scripts\activate.bat" %ENV_NAME%
    echo cd /d "%PROJECT_ROOT%"
    echo python main.py %%*
) > "%DESKTOP_LAUNCHER%"

REM ---- 4. Optional SAM-HeLa checkpoint path -----------------------
echo.
echo [install] Optional: if you already have sam_hela\best.pt on disk,
echo [install] you can point the app at it now. Press Enter to skip --
echo [install] you can configure it later in the app's I/O settings.
set /p "MODEL_PATH=  Path to best.pt (or empty to skip): "
if not "%MODEL_PATH%"=="" (
    call conda activate "%ENV_NAME%"
    python "%SCRIPT_DIR%configure_model.py" "%MODEL_PATH%" || (
        echo [install] (path not saved; you can set it later in the app settings)
    )
)

echo [install] Done. Double-click EyeDataLabeller on your Desktop to launch.
endlocal
exit /b 0

:fail
echo [install] FAILED. See messages above.
endlocal
exit /b 1
